development:
  secret_key_base: ef3474241677eb80ccad77e71ae48b3315671c55b2a55307df4ea62dbec6150450017fabf106eb7902695c04225dde1f6691c5400d49f4d228f2dd208981328c
  google_api_key: AIzaSyAvnqaAFuiAlXMuFIaPGWkRgmnxSmLII3o
  host: localhost
  url: http://localhost:5000

test:
  secret_key_base: ef3474241677eb80ccad77e71ae48b33
  google_api_key: nokey
  host: localhost
  url: http://localhost:5000

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_api_key: <%= ENV["GOOGLE_API_KEY"] %>
  host: moi-staging.herokuapp.com
  url: https://moi-staging.herokuapp.com

integration:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_api_key: <%= ENV["GOOGLE_API_KEY"] %>
  host: moi-integration.herokuapp.com
  url: https://moi-integration.herokuapp.com

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_api_key: <%= ENV["GOOGLE_API_KEY"] %>
  delayed_job_user: <%= ENV["DELAYED_JOB_USER"] %>
  delayed_job_password: <%= ENV["DELAYED_JOB_PASSWORD"] %>
  host: moi-backend.growmoi.com
  url: http://moi-backend.growmoi.com
